all:
	@echo 'please supply a day number'

1:
	@nodejs day_1.js

2:
	@ruby day_2.rb

3:
	@clang -o day_3.out day_3.c
	@./day_3.out
	@rm day_3.out

4:
	@ghc -o day_4.out day_4.hs
	@./day_4.out
	@rm day_4.out day_4.hi day_4.o

%:
	@echo 'unknown day number'
