all:
	@echo 'please supply a day number'

1:
	@../run.sh day_01.js

2:
	@../run.sh day_02.rb

3:
	@../run.sh day_03.c

4:
	@../run.sh day_04.hs

5:
	@../run.sh day_05.py

6:
	@../run.sh day_06.hs

7:
	@../run.sh day_07.pl

8:
	@../run.sh day_08.rs

9:
	@../run.sh day_09.py

10:
	@../run.sh day_10.py

11:
	@../run.sh day_11.rs

12:
	@../run.sh day_12.c

13:
	@../run.sh day_13.lua

14:
	@../run.sh day_14.rb

15:
	@../run.sh day_15.cpp

18:
	@../run.sh day_18.hs

19:
	@../run.sh day_19.rs

%:
	@echo 'unknown day number'
