all:
	@echo 'please supply a day number'

1:
	@../run.sh day_01.hs

2:
	@../run.sh day_02.sh

3:
	@../run.sh day_03.rb

4:
	@../run.sh day_04.js

5:
	@../run.sh day_05.py

6:
	@../run.sh day_06.rs

7:
	@../run.sh day_07.rb

8:
	@../run.sh day_08.jl

9:
	@../run.sh day_09.go

10:
	@../run.sh day_10.py

11:
	@../run.sh day_11.rs

%:
	@echo 'unknown day number'
