all:
	@echo 'please supply a day number'

1:
	@../run.sh day_01.hs

2:
	@../run.sh day_02.sh

3:
	@../run.sh day_03.rb

4:
	@../run.sh day_04.js

5:
	@../run.sh day_05.py

%:
	@echo 'unknown day number'
