all:
	@echo 'please supply a day number'

1:
	@../run.sh day_01.ck

2:
	@../run.sh day_02.sh

3:
	@../run.sh day_03.pl

4:
	@../run.sh day_04.go

5:
	@../run.sh day_05.jl

6:
	@../run.sh day_06.zig

7:
	@../run.sh day_07.c

8:
	@../run.sh day_08.rb

%:
	@echo 'unknown day number'
